name: 'Setup Global Akka Resolver'
description: 'Sets up a global Akka resolver for sbt, Maven, and Gradle.'
inputs:
  sbt-plugin-project-name:
    description: 'The name of the sbt plugin project to configure scripted tests for.'
    required: false
    default: ''
  maven-mirror-control:
    description: 'Controls the Maven mirror configuration. Set to NO_MIRROR to skip mirror setup.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/../setup_global_resolver.sh "${{ inputs.sbt-plugin-project-name }}" "${{ inputs.maven-mirror-control }}"
      shell: bash
